# fly.toml app configuration file generated for spencergreene on 2023-07-09T20:17:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spencergreene"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/up"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = true
    [services.http_checks.headers]

